Update main_asistencia-api-itvh.yml

diff --git a/.github/workflows/main_asistencia-api-itvh.yml b/.github/workflows/main_asistencia-api-itvh.yml
--- a/.github/workflows/main_asistencia-api-itvh.yml
+++ b/.github/workflows/main_asistencia-api-itvh.yml
@@ -193,8 +193,20 @@ jobs:
         uses: azure/cli@v2
         with:
           inlineScript: |
-            # Configure startup command
-            az webapp config set --name asistencia-api-itvh --resource-group $(az webapp show --name asistencia-api-itvh --query resourceGroup --output tsv) --startup-file /home/site/wwwroot/startup.sh
+            # Obtener el nombre del Resource Group
+            RESOURCE_GROUP=$(az webapp show --name asistencia-api-itvh --query resourceGroup --output tsv)
+      
+            # Verificar si se obtuvo correctamente
+            if [ -z "$RESOURCE_GROUP" ]; then
+              echo "ERROR: No se pudo obtener el Resource Group."
+              exit 1
+            fi
+      
+            echo "Resource Group encontrado: $RESOURCE_GROUP"
+      
+            # Configurar el comando de inicio
+            az webapp config set --name asistencia-api-itvh --resource-group $RESOURCE_GROUP --startup-file /home/site/wwwroot/startup.sh
+
       
       - name: Deploy to Azure Web App
         uses: azure/webapps-deploy@v3
